import { ColorDirection } from "./enum"

export interface PointType {
    x: number,
    y: number,
    color?: string, // post generated by nee_color
}

export interface OptionsType {
    screenArea?: ScreenOptions,
    initialPoint?: PointType,
    endPoints?: Array<PointType>
    intervalLimits?: LimitsType,
    color?: ColorsOptions,
}

export interface ScreenOptions {
    min: {
        x: number,
        y: number,
    },
    max: {
        x: number,
        y: number
    }
}

export interface LimitsType {
    min: number,
    max: number
}

export interface DeltaTimeType {
    previousTime: number,
    delta: number,
}

export interface ColorsOptions {
    colors: Array<string> | string,
    direction?: ColorDirection,
    disolve?: boolean, // turns the gradient transparent through the colors
}